### ISSUE TITLE
Run two or more X-Plane at one computer

### ISSUE THREAD

**Issue by racso10** [nasa/XPlaneConnect#127]
I use function [setCONN ](https://github.com/nasa/XPlaneConnect/blob/master/Python/src/xpc.py)by python to change one X-Plane port, and use this port to control plane.  Then I open another X-Plane, using its default port(49009),  but I cannot control it, I control the plane which I changed port! It looks like I control one plane using two port.
Why?
And what should I do if I want to control two plane in one computer?

**Comment by jason-watkins** [comment]
Hi racso,

The `secCONN` function is used to change the port used on the client side. The plugin side always uses 49009. Because of this, it is not currently possible to run two instances of the X-Plane Connect plugin on the same computer.

As a workaround, you can compile the plugin twice with different values for [RECVPORT](https://github.com/nasa/XPlaneConnect/blob/master/xpcPlugin/XPCPlugin.cpp#L73).

There's no technical reason the server can't be asked to change ports, but I don't have time to implement that command myself. We do accept pull requests though.

**Comment by racso10** [comment]
Thank you!
I do it and run three X-Plane in one computer.
