### ISSUE TITLE
pauseSim()

### ISSUE THREAD

**Issue by shanccshuirr** [nasa/XPlaneConnect#241]
Dear Mr. Watkins

 

I’m a user who has been using XPlaneConnect plugin to transmit data between my own model in C code and XPlane model. I run into a problem that I don’t have any clues to fix so I’m to inquire some possible help from you.

 

My problem is with the code pauseSim(,0). When I use this code to control spoilers and flaps to respond to my C code model outside of XPlane, the spoilers and flaps of the airplane function and respond well and correctly to my C code model, but the same airplane inside of XPlane is constantly shaking around, and it seems that there is no way to stop this shaking. Is there any way to stop this shaking or go around this problem?  Please let me know and thank you very much.

OR

If I change the code pauseSim(,0) to pauseSim(,1), neither spoilers nor flaps of the very same airplane move or respond to my C code model. Is there any way to fix this problem?

 

I just need to move and control spoilers and flaps in XPlane using my own C code model, so either one of the above solutions can solve my problem. Your help and support is highly appreciated. Please let me know if there is anything wrong in my code.

 

Thank you very much for your support

Best Regards,

Jesse

**Comment by epaton2** [comment]
Hello Jesse,  Perhaps I can answer for Jason.  I am not sure what would be causing the shake in X-Plane, but I'm assuming the X-Plane flight model is fighting spoiler and flap commands you are attempting to set.  Instead of using pauseSim, I would use the override_planepath dataref and setDREF function,  which freezes the XPlane flight model.   If this does not work, you can try some of the other override datarefs listed in datarefs.txt.
