### ISSUE TITLE
I got this error when I used matlab :Error using XPlaneConnect.getDREFs (line 27) [getDREFs] ERROR: Multiple clients open. You must specify which client to use.

### ISSUE THREAD

**Issue by magedmikhail** [nasa/XPlaneConnect#76]

**Comment by jason-watkins** [comment]
Hi magedmikhail.

This is usually caused by calling `openUDP` more than once, and not specifying which socket you want to use in subsequent calls.

Could you post an [SSCCE](http://sscce.org/)?

**Comment by magedmikhail** [comment]
Dear all
please Can you tell me the  steps to set the connection between matalb and
x plane.

1. I have  - x Plane 10 ready

2.  I Copied the X-Plane Plugin folder (xpcPlugin/XPlaneConnect) to the
plugin directory ([X-Plane Directory]/Resources/plugins/)

3. matlab ready for Example1

what I should to do for x plane setting option for input output and net
connection(IP  for data output and UDP) how you set them up  to match with
matlab

Socket = openUDP( 49005); is this correct or Socket = openUDP(
'127.0.0.1',49005);

getDREFs('sim/test/test_float')  (My problem here)











On Tue, Jun 16, 2015 at 2:12 PM, Jason Watkins <notifications@github.com>
wrote:

> Hi magedmikhail.
>
> This is usually caused by calling openUDP more than once, and not
> specifying which socket you want to use in subsequent calls.
>
> Could you post an SSCCE <http://sscce.org/>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nasa/XPlaneConnect/issues/76#issuecomment-112532700>.
>



-- 

Thanks,
Dr. Maged mikhail
Maged B. Mikhail  Ph.D.
Tennessee State University
Dept. of Electrical and Computer Engr.
Intelligent Control Systems Lab Rm. 201
Work: (615) 963-5328
Cell: (615) 710-6745
E_mail: mmikhail@my.tnstate.edu <mmikhail@mytsu.tnstate.edu>

**Comment by jason-watkins** [comment]
`Socket = openUDP( 49005);` does appear to be a bug in the sample script. I have corrected it for the next release. `Socket = openUDP( '127.0.0.1',49005);` is indeed correct.

Could you verify that you get the same error with a freshly opened copy of MATLAB? Because the example script does not include robust error handling, it's possible for sockets to be abandoned but left open if some other error causes the example script to exit early.

**Comment by teubert** [comment]
Hello Maged Mikhail,

Were you able to get this working? I wanted to check in and make sure you got all your questions answered.

~Chris

**Comment by dangmoran1991** [comment]
Got the same problem here, and can not solve....
I also have:
1.  x Plane 10 ready
2.  I Copied the X-Plane Plugin folder (xpcPlugin/XPlaneConnect) to the
plugin directory ([X-Plane Directory]/Resources/plugins/)
3. matlab ready for Example1

and the problem is like:
![image](https://cloud.githubusercontent.com/assets/13197736/8519687/1ead018a-2407-11e5-90c1-a2dff411142b.png)


Thank you.
Moran

**Comment by jason-watkins** [comment]
Hi Moran.

I've just pushed an update to the repository that fixes several issues with the MATLAB example script. Could you update to the latest version of master and let me know if it works for you?

Thanks,
Jason

**Comment by jason-watkins** [comment]
@ magedmikhail @dangmoran1991 

Since I haven't heard anything more, I'm going to hope that no news is good news and you've both gotten things up and running. Feel free to comment here or open a new issue if we can provide any additional help.

Thanks,
Jason
