### ISSUE TITLE
Determine Python Architecture

### ISSUE THREAD

**Issue by teubert** [nasa/XPlaneConnect#8]

**Comment by RobertLos** [comment]
Hi Jason,
great piece of work. I have been trying to get a python interface towards x-plane 10 (steam edition on ubuntu 14.04 64 bits) and stumbled over de nasa plugin.
I use pycharm for my (professional) python work and found a few issues in the code which I would like to share with you. Mostly pep-8 related but also some parameters which are not used or of the wrong type.
My goal is to write a moving map application using QT5 as a gui.
Largest issues I found:
def read_pos(self, result_array, gear):   # TODO parameters are not used
def read_ctrol(self, result_array, gear):   # TODO parameters are superfluous
in parse_dref: len_val = struct.unpack_from("B", msg, 6 + len_dref)    # TODO solve type error in len_dref
in send_dref: msg_len is not used
in parse_getd: len_list in the range function is not of the correct type
def read_request(self, recv_addr):  # TODO parameter recv_addr not used

When I can help, please let me know how I can share in the effort. I use Python 3.4 since that is better for working with QT5

greetings

**Comment by jason-watkins** [comment]
Hi Robert. 

Thanks for your feedback. As you can see from the commit history, it has been quite some time since I touched the Python client. At the time I wrote it, I had very little experience with both X-Plane and X-Plane Connect. I've been working on X-Plane Connect full time for the last month, so I have a much better idea now of how the Python client should work.

We are currently working on internal code review for the 1.0 release, so it may be a few days before I can get back to this. It happens that cleaning up the Python client and getting it ready for release is next on my to-do list after we finalize the 1.0 release, so I'll take a look at the issues you noted as soon as I can next week.

**Comment by jason-watkins** [comment]
Hey @RobertLos,

Sorry it took me all week to get back to this. I've fixed up all of the issues with the client that I could find, and added tests to cover our common use cases.

Unfortunately we need to support Python 2.x, so that's what I'm targeting right now. I'm not opposed to adding support for 3.x, but I would really like to find a way to do that without having to maintain two completely separate modules. I don't do a lot of work in Python, so I don't know whether there are common ways to accomplish this that are used in the Python community. Do you have any ideas?

**Comment by RobertLos** [comment]
Hi Jason,

Sorry from myside also to reply this late. Have been on a holiday to Paris.
The syntax differences between python 2 and 3 are not too dramatic. You 
can coe in python3 style (parenthesis around strings in print 
statements, etc) and python 2 will still accept that. You can
Why do you need python 2.x? The only reason I can think of is that you 
are using some library that needs 2.x. Look at 
https://wiki.python.org/moin/Python2orPython3 for a discussion.

For my work I have setup a jenkins based continuous integration 
environment for python development (well actually jython wlst for oracle 
weblogic deployment). It gives good feedback on code quality and style. 
If youm like we can try to setup a ci enviironment that does some 
monitoring on the development.

greetings

Robert

Robert Los Commercial & Contract Services
Nachtegaallaan 46
3055 CS Rotterdam
The Netherlands
T: +31 10 2857015
M:+31 6 24893872
E: robert@robertlos.nl <mailto:robert@robertlos.nl>
www.robertlos.nl <http://www.robertlos.nl>
